### ISSUE TITLE
Cannot use wiki plugin

### ISSUE THREAD

**Issue by mzwlevi** [enchantmenttable/logseq-wiki-search#2]
<img width="431" alt="Screen Shot 2022-10-19 at 18 54 23" src="https://user-images.githubusercontent.com/78029539/196672407-a7eb59ed-64be-4b83-9441-e8c5aa3fc0db.png">

<img width="475" alt="Screen Shot 2022-10-19 at 18 54 38" src="https://user-images.githubusercontent.com/78029539/196672423-c8075449-18cd-4094-89de-2cc131e08daa.png">

Logseq version: 0.8.8

**Comment by feigaoxyz** [comment]
same issue on Logseq v0.8.10 + plugin v0.0.4

**Comment by enchantmenttable** [comment]
Sorry haven't figured out how to solve this issue. If anyone knows how to fix it, please help and create a pull request. It'll be much appreciated!

**Comment by astubbs** [comment]
Same on Version 0.8.15 (0.8.15)

**Comment by pat-githubber** [comment]
I still have the problem and I am not bright enough to understand https://github.com/enchantmenttable/logseq-wiki-search/pull/3#issue-2172772047

Logseq version: 0.10.9
Search Wikipedia version: 0.0.4
